# Data exploration

data:
  raw:
    CheXpert: 
      root_path: "/mnt/c/Users/Masia/OneDrive/Desktop/Project-Hippocrates-X/data/raw/CheXpert"
      img_data: "/mnt/c/Users/Masia/OneDrive/Desktop/Project-Hippocrates-X/data/raw/CheXpert"
      csv_train:  "${.root_path}/train.csv"
      csv_val: "${.root_path}/valid.csv"
      batch_size: 32

  processed:
    CheXpert:
      parquet: "/mnt/c/Users/Masia/OneDrive/Desktop/Project-Hippocrates-X/data/processed/chexpert/dataset_u_ignore__null_missing__nf_derive.parquet"

label_cols:
  - No Finding
  - Enlarged Cardiomediastinum
  - Cardiomegaly
  - Lung Opacity
  - Lung Lesion
  - Edema
  - Consolidation
  - Pneumonia
  - Atelectasis
  - Pneumothorax
  - Pleural Effusion
  - Pleural Other
  - Fracture
  - Support Devices

variants:
  u_ignore__null_missing__nf_derive:
    null_handling: missing          # keep null as missing
    uncertain_handling: ignore      # mask out -1 from loss
    no_finding:
      mode: derive                 # derive from other labels
      derive_from: all_except_no_finding
      # if all other labels are observed-as-negative and none positive => No Finding=1
      # if any other label positive => No Finding=0
      require_observed_other_labels: 1  # if not enough info, set No Finding to missing

  u_zero__null_negative__nf_keep_original:
    null_handling: negative         # treat null as 0
    uncertain_handling: zero        # map -1 -> 0
    no_finding:
      mode: keep_original           # keep No Finding as is (not recommended, but useful baseline)

  u_soft05__null_missing__nf_drop:
    null_handling: missing
    uncertain_handling: soft        # map -1 -> 0.5 (still learn)
    uncertain_soft_value: 0.5
    no_finding:
      mode: drop                    # do not train No Finding at all
